todo push

diff --git a/.github/workflows/DeployTesting.yml b/.github/workflows/DeployTesting.yml
--- a/.github/workflows/DeployTesting.yml
+++ b/.github/workflows/DeployTesting.yml
@@ -30,8 +30,9 @@ jobs:
         run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
 
       - name: Creating issues
-        run: readarray -t array <<< $(git diff HEAD^ --name-only -G " TODO" -- ':!:*.yml' | xargs --no-run-if-empty git grep " TODO" --) &&
-              for command in "${array[@]}"; do     gh issue create --title "${command##*#}" --body "${command}" --label "todo"; done
+        run: readarray -t array <<< $(git diff HEAD^ --name-only -G " TODO" -- ':!:*.yml' | xargs --no-run-if-empty git
+                grep " TODO" --) && for command in "${array[@]}"; do
+                    gh issue create --title "${command##*#}" --body "${command}" --label "todo" || echo "ERROR"; done
 
       - name: Github logout
         run: gh auth logout --hostname github.com
