Workflow changes

diff --git a/.github/workflows/DeployTesting.yml b/.github/workflows/DeployTesting.yml
--- a/.github/workflows/DeployTesting.yml
+++ b/.github/workflows/DeployTesting.yml
@@ -4,43 +4,9 @@ name: Deploy testing to Heroku-dev
     branches:
       - testing
 jobs:
-  Clone:
-    runs-on: self-hosted
-    steps:
-      - uses: actions/checkout@v2
-        with:
-            fetch-depth: 0
-
-      - name: Checking out testing branch
-        run: git checkout testing
-
-      - name: Loading & Checking committer
-        run: committer=$(git log -1 --pretty=format:'%an');
-              echo "$committer"; if [ "$committer" = "Github runner" ]; then
-                  exit 2;
-              else
-                  exit 0;
-              fi
-
-  Create-issues-using-TODO:
-    runs-on: self-hosted
-    needs: Clone
-    steps:
-      - name: Github login
-        run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
-
-      - name: Creating issues
-        run: readarray -t array <<< $(git diff HEAD^ --name-only -G "TODO" -- ':!:*.yml' | xargs --no-run-if-empty git
-                grep -n "TODO" --) && for command in "${array[@]}"; do
-                    gh issue create --title "${command##*#}" --body "${command}" --label "todo" || echo "ERROR $(command)";
-                      done
-
-      - name: Github logout
-        run: gh auth logout --hostname github.com
 
   Deploy-testing-to-Heroku:
     runs-on: self-hosted
-    needs: Clone
     steps:
       - uses: actions/checkout@v2
         with:
@@ -81,5 +47,20 @@ jobs:
                     git push heroku-dev -f testing:main
 
       - name: Pushing to Github
-        run: cd ${{ github.workspace }} && eval `ssh-agent -s` && ssh-add ~/.ssh/github &&
-              git push
+        run: git push
+
+  Create-issues-using-TODO:
+    runs-on: self-hosted
+    needs: Deploy-testing-to-Heroku
+    steps:
+      - name: Github login
+        run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
+
+      - name: Creating issues
+        run: readarray -t array <<< $(git diff HEAD^ --name-only -G "TODO" -- ':!:*.yml' | xargs --no-run-if-empty git
+                grep -n "TODO" --) && for command in "${array[@]}"; do
+                    gh issue create --title "${command##*#}" --body "${command}" --label "todo" || echo "ERROR $(command)";
+                      done
+
+      - name: Github logout
+        run: gh auth logout --hostname github.com
